# Generated by Django 5.2.5 on 2025-09-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='validity',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
