# Generated by Django 5.2.5 on 2025-09-01 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0003_urlclick'),
    ]

    operations = [
        migrations.DeleteModel(
            name='URLClick',
        ),
    ]
